[username]
format = " [╭─$user]($style)@"
style_user = "bold green"
style_root = "bold green"
show_always = true

[hostname]
format = "[$hostname]($style) in "
style = "bold green"
trim_at = "-"
ssh_only = false
disabled = false

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = " [╰─λ](bold green)"
error_symbol = " [×](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"
